name: Generación CHANGELOG.md

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please Action
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          package-name: changelog-auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
