name: Generación CHANGELOG.md

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detectar y cambiar a la rama del release o crear una temporal
        run: |
          git fetch origin
          BRANCH="${{ github.event.release.target_commitish }}"

          # Si es una rama, cambiamos a ella
          if git ls-remote --heads origin $BRANCH | grep $BRANCH; then
            echo "Cambiando a la rama $BRANCH"
            git checkout $BRANCH
          else
            echo "No es una rama. Creamos rama temporal desde el tag/commit."
            git checkout -b temp-release-branch
          fi

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache de npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar CLI de changelog globalmente
        run: npm install -g conventional-changelog-cli

      - name: Crear archivo changelog si no existe
        run: |
          if [ ! -f CHANGELOG.md ]; then
            touch CHANGELOG.md
          fi

      - name: Generar/Actualizar el changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Hacer commit y push del changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: actualizo changelog tras release" || echo "Sin cambios para commitear"
          git push origin HEAD:${{ github.event.release.target_commitish }} || echo "No se pudo pushear a la rama original, quizás fue un tag directo."

