name: Generación CHANGELOG.md

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache de npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar CLI de changelog globalmente
        run: npm install -g conventional-changelog-cli

      - name: Crear archivo changelog si no existe
        run: |
          if [ ! -f CHANGELOG.md ]; then
            touch CHANGELOG.md
          fi

      - name: Generar/Actualizar el changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Hacer commit y push del changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: actualizo changelog tras release" || echo "No hay cambios para commitear"
          git pull --rebase
          git push origin HEAD:${{ github.ref_name }}
